### ISSUE TITLE
[Bug]: When used with `Atom Material Icons`, `Current Theme` option has no effect

### ISSUE THREAD

**Issue by xsjcTony** [doki-theme/doki-theme-icons-jetbrains#109]
### Your Environment

PhpStorm 2023.2.3
Build #PS-232.10072.32, built on October 14, 2023
Licensed to ******
You have a perpetual fallback license for this version.
Subscription is active until September 6, 2024.
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    run.processes.with.pty=TRUE
    nodejs.console.use.terminal=false
    ide.images.show.chessboard=true
    typescript.external.type.definitions.packages=express,lodash,mocha,chai,jasmine,react-dom,react-router-dom,styled-components,react-native
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    io.unthrottled.doki.icons (88.5-1.0.13)
    com.nasller.CodeGlancePro (1.7.6)
    com.notime.intellijPlugin.backgroundImagePlus (1.0.3)
    com.myoutdesk.tailwind_formatter (2.0.8)
    com.github.copilot (1.3.3.3572)
    quokka.js (1.0.406)
    cn.olange.rule (1.0.5.2)
    com.chesterccw.excelreader (2023.6.1-222.232)
    one.util.ideaplugin.screenshoter (1.8.1)
    com.markskelton.one-dark-theme (5.9.0)
    String Manipulation (9.11.3)
    Key Promoter X (2023.2.0)
    com.wakatime.intellij.plugin (14.3.1)
    com.intellij.kubernetes (232.10072.33)
    ru.adelf.idea.dotenv (2023.2)
    net.seesharpsoft.intellij.plugins.csv (3.2.3-232)
    org.intellij.prisma (232.9559.10)
    com.github.aleksandrsl.intellijbrowserslist (1.0.2)
    izhangzhihao.rainbow.brackets (2023.3.7)
    me.rerere.unocss-intellij (1.3.7)
    dev.blachut.svelte.lang (232.9921.36)
    com.github.lppedd.idea-return-highlighter (0.8.3)
    com.jetbrains.lang.ejs (232.8660.142)
    cn.yiiguxing.plugin.translate (3.5.5)
    com.laravel_idea.plugin (7.4.3.232)
    com.mallowigi (93.1.0)
    mobi.hsz.idea.gitignore (4.5.2)

### How to reproduce.

1. Have both `Doki Theme Icons` and `Atom Material Icons` installed.
2. Check `UI Icons` in `Doki Theme Icon Settings`:
![Snipaste_2023-11-06_21-23-16](https://github.com/doki-theme/doki-theme-icons-jetbrains/assets/45784210/0dc2d547-499c-419a-a050-11442f38067a)
3. Uncheck `Enable UI Icons` in `Atom Material Icons Settings`: 
![Snipaste_2023-11-06_21-23-10](https://github.com/doki-theme/doki-theme-icons-jetbrains/assets/45784210/270f32d7-2558-4fc2-ac5e-b47d15985b18)

### What is expected?

The theme of UI icons should take effect, however it always default to the blue one.
![Snipaste_2023-11-06_21-23-50](https://github.com/doki-theme/doki-theme-icons-jetbrains/assets/45784210/a5a43798-1085-42d8-9ec6-c9d100914354)

**Comment by xsjcTony** [comment]
This is the error log, no idea if it's related.
```
com.intellij.diagnostic.PluginException: No display name specified in plugin descriptor XML file for configurable io.unthrottled.doki.icons.jetbrains.settings.IconSettingsUI;
specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: io.unthrottled.doki.icons]
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:156)
	at com.intellij.openapi.options.ex.Weighted.lambda$static$0(Weighted.java:26)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:221)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at com.intellij.openapi.options.ex.SortedConfigurableGroup.buildConfigurables(SortedConfigurableGroup.java:41)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:75)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:148)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:110)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:119)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$Companion.getConfigurableGroups(ShowSettingsUtilImpl.kt:48)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.kt)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$myActionProcessor$1.performAction(IdeKeyEventDispatcher.kt:502)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$5$lambda$4(IdeKeyEventDispatcher.kt:865)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$5(IdeKeyEventDispatcher.kt:865)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:863)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:454)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:447)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:309)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:622)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:591)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by Unthrottled** [comment]
Thanks for reporting, but I am not going to support the plugin with the Atom Material Icons. They both use the same internal api, so they don't play nicely together. Have one or the other installed. If you disable/remove the material icons plugin (like the actual plugin and not the setting) the theming will work.
