### ISSUE TITLE
[Bug]: Recursive update in ConcurrentHashMap

### ISSUE THREAD

**Issue by NekoCaffeine** [doki-theme/doki-theme-icons-jetbrains#17]
### Your Environment

```stacktarce
Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create class io.unthrottled.doki.icons.jetbrains.shared.listeners.ApplicationLifecycleListener (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Doki Theme Icons, id=io.unthrottled.doki.icons, descriptorPath=plugin.xml, path=D:\JetBrains\Toolbox\apps\IDEA-C\ch-0\223.8214.27.plugins\Doki Theme Icons, version=88.3-1.0.2, package=null, isBundled=false), packagePrefix=null, instanceId=20, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:989)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:1027)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners$lambda$3(CompositeMessageBus.kt:118)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:224)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:232)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.kt:112)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers(CompositeMessageBus.kt:93)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers(MessageBusImpl.kt:192)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers(CompositeMessageBus.kt:88)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher$publish$handlers$1.invoke(CompositeMessageBus.kt:260)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher$publish$handlers$1.invoke(CompositeMessageBus.kt:260)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$lambda$0(CompositeMessageBus.kt:260)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:260)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:430)
	at jdk.proxy2/jdk.proxy2.$Proxy95.appFrameCreated(Unknown Source)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded$suspendImpl(IdeStarter.kt:91)
	at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt)
	at com.intellij.idea.IdeStarter$start$2.invokeSuspend(IdeStarter.kt:72)
	at com.intellij.idea.IdeStarter$start$2.invoke(IdeStarter.kt)
	at com.intellij.idea.IdeStarter$start$2.invoke(IdeStarter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.idea.IdeStarter.start$suspendImpl(IdeStarter.kt:70)
	at com.intellij.idea.IdeStarter.start(IdeStarter.kt)
	at com.intellij.idea.ApplicationLoader.initApplicationImpl(ApplicationLoader.kt:169)
	at com.intellij.idea.ApplicationLoader.access$initApplicationImpl(ApplicationLoader.kt:1)
	at com.intellij.idea.ApplicationLoader$initApplicationImpl$1.invokeSuspend(ApplicationLoader.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ExceptionInInitializerError
	at io.unthrottled.doki.icons.jetbrains.shared.listeners.ApplicationLifecycleListener.<clinit>(ApplicationLifecycleListener.kt:12)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:950)
	... 38 more
Caused by: java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1167)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at com.intellij.util.messages.impl.MessageBusImpl.notifyOnSubscription(MessageBusImpl.kt:199)
	at com.intellij.util.messages.impl.BaseBusConnection.subscribe(BaseBusConnection.kt:41)
	at io.unthrottled.doki.icons.jetbrains.shared.path.IconPathReplacementComponent.initialize(IconPathReplacementComponent.kt:51)
	at io.unthrottled.doki.icons.jetbrains.shared.integrations.PlatformHacker.<clinit>(PlatformHacker.kt:15)
	... 42 more

```

```
IntelliJ IDEA with Maho 2022.3.1 RC (Community Edition)
Build #IC-223.8214.27, built on December 15, 2022
Runtime version: 17.0.4+8-LTS amd64
VM: OpenJDK 64-Bit Server VM by SAP SE
Windows 10 10.0
GC: Shenandoah Pauses, Shenandoah Cycles
Memory: 16384M
Cores: 32
Registry:
    ide.intellij.laf.enable.animation=true
    debugger.watches.in.variables=false
    ide.tooltip.initialDelay=0
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    io.acari.DDLCTheme (88.3-1.8.0)
    amadeus.maho (223.8214.27)
    io.unthrottled.doki.icons (88.3-1.0.2)

Kotlin: 223-1.7.21-release-272-IJ8214.27
```

### How to reproduce.

startup intellij

### What is expected?

no exception occurred

**Comment by Unthrottled** [comment]
I was able to reproduce the issue using a non-bundled runtime. Will look into the fix, thanks for reporting.

**Comment by Unthrottled** [comment]
Side note, do the icons look blurry & the menu-bar isn't themed?

![image](https://user-images.githubusercontent.com/15972415/208336635-174ae484-7c57-456f-b09b-3672bc121811.png)

**Comment by NekoCaffeine** [comment]
![image](https://user-images.githubusercontent.com/10548315/208670744-620bdb9e-e7b8-46d6-bcf0-26798e2bda85.png)
There doesn't seem to be blurring in my environment, the title bar and menu bar are fixed by my plugin.
